plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'androidx.navigation.safeargs.kotlin'
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.serialization)

}
android {
    namespace = "com.vocabulary.myvocabulary"
    compileSdkVersion 36
    defaultConfig {
        applicationId "com.vocabulary.myvocabulary"
        minSdkVersion 23
        targetSdkVersion 36
        versionCode 32
        versionName "1.3"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix '.debug'
            debuggable true
        }
    }

    kapt {
        arguments {
            arg("room.schemaLocation", "$projectDir/schemas".toString())
        }
    }

    buildFeatures {
        viewBinding true
        buildConfig true
        compose = true
    }

    kotlin {
        jvmToolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }
}

dependencies {
    implementation libs.androidx.lifecycle.viewmodel.ktx
    def room_version = "2.8.2"
    def lifecycle_version = "2.2.0"
    def nav_version = "2.9.5"
    def lottie_version = "6.6.10"
    def constraint_layout_version = "2.2.1"
    def material_version = "1.13.0"
    def card_view_version = "1.0.0"
    def rx_android_version = "2.1.1"
    def rx_java_version = "2.2.21"
    def junit_version = "4.13.2"
    def androidx_test_version = "1.7.0"
    def espresso_version = "3.7.0"
    def mockito_core_version = "5.20.0"
    def mockito_kotlin_version = "2.2.0"
    def assertj_core_version = "3.27.6"
    def material_about_version = "0.2.3"
    def rx_preferences_version = "2.0.1"
    def retrofit_version = "3.0.0"
    def apache_csv_version = "1.14.1"
    def groupie_version = "2.10.1"
    def sandbox_version = "1.0.0-alpha13"
    def nav_latest_version = "2.9.6"

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "androidx.constraintlayout:constraintlayout:$constraint_layout_version"
    implementation "com.google.android.material:material:$material_version"
    implementation "androidx.cardview:cardview:$card_view_version"

    //Room
    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-rxjava2:$room_version"

    //RxJava
    implementation "io.reactivex.rxjava2:rxandroid:$rx_android_version"
    implementation "io.reactivex.rxjava2:rxjava:$rx_java_version"

    //Retrofit
    implementation "com.squareup.retrofit2:retrofit:$retrofit_version"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"
    implementation "com.squareup.retrofit2:adapter-rxjava2:$retrofit_version"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"

    //Espresso
    testImplementation "junit:junit:$junit_version"
    androidTestImplementation "androidx.test:runner:$androidx_test_version"
    androidTestImplementation "androidx.test:rules:$androidx_test_version"
    androidTestImplementation "androidx.test.espresso:espresso-core:$espresso_version"
    androidTestImplementation "androidx.test.espresso:espresso-contrib:$espresso_version"

    //Mockito
    testImplementation "org.mockito:mockito-core:$mockito_core_version"
    testImplementation "com.nhaarman.mockitokotlin2:mockito-kotlin:$mockito_kotlin_version"
    testImplementation "androidx.arch.core:core-testing:$lifecycle_version"
    testImplementation "org.assertj:assertj-core:$assertj_core_version"

    //Navigation
    implementation libs.androidx.ktx
    implementation "androidx.navigation:navigation-fragment:$nav_latest_version"
    implementation "androidx.navigation:navigation-ui:$nav_latest_version"

    //Navigation compose
    implementation "androidx.navigation:navigation-compose:$nav_latest_version"

    //Koin
//    implementation "io.insert-koin:koin-core:$koin_core_version"
//    implementation "io.insert-koin:koin-android:$koin_core_version"


    //Lottie animation
    implementation "com.airbnb.android:lottie:$lottie_version"

    //About page
    implementation "com.github.jrvansuita:MaterialAbout:$material_about_version"

    //Share preferences
    implementation "com.f2prateek.rx.preferences2:rx-preferences:$rx_preferences_version"

    //Apache CSV
    implementation "org.apache.commons:commons-csv:$apache_csv_version"

    //Groupie
    implementation "com.github.lisawray.groupie:groupie:$groupie_version"
    implementation "com.github.lisawray.groupie:groupie-viewbinding:$groupie_version"

    //Google Play Core Library
    implementation libs.core.ktx

    implementation "androidx.privacysandbox.tools:tools:$sandbox_version"
    implementation "androidx.privacysandbox.tools:tools-apicompiler:$sandbox_version"
    implementation "androidx.privacysandbox.tools:tools-apigenerator:$sandbox_version"
    implementation "androidx.privacysandbox.tools:tools-core:$sandbox_version"
    implementation "androidx.privacysandbox.tools:tools-apipackager:$sandbox_version"

    //Compose
    def composeBom = platform('androidx.compose:compose-bom:2025.10.01')
    implementation composeBom
    androidTestImplementation composeBom
    implementation libs.androidx.material3
    implementation libs.androidx.ui.tooling.preview
    debugImplementation libs.androidx.ui.tooling
    androidTestImplementation libs.androidx.ui.test.junit4
    debugImplementation libs.androidx.ui.test.manifest
    implementation libs.androidx.adaptive
    implementation libs.androidx.activity.compose
    implementation libs.androidx.runtime.livedata
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.androidx.runtime.rxjava2
    implementation libs.androidx.compose.material.iconsExtended
    implementation libs.koin.android
    implementation libs.koin.androidx.compose
    implementation libs.koin.core
    implementation libs.koin.compose



}
